testing go yml file, adding formats

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -26,7 +26,20 @@ jobs:
 
       - name: Test
         run: go test ./... -v 
+      
+      - name: Analyze Test Results
+        if: failure() 
+        run: go test./.. -v | sed ''/PASS/s//$(printf "\033[32mPASS\033[0m")/'' | sed ''/FAIL/s//$(printf "\033[31mFAIL\033[0m")/'' && 
+          go test ./... -v > test-output.log &&
+          if grep -q "FAIL" test-output.log; then
+            echo "Tests failed"
+            exit 1
+          else
+            echo "All tests passed"
+          fi  
 
       - name: Code Coverage Test
         if: success()
         run: go test -coverprofile=coverage.out ./... && go tool cover -html=coverage.out
+
+      
